language: python
python:
  - "3.8"
# command to install dependencies
install: "pipenv install"
# command to run tests
script: sh run_tests.sh

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#fedora-apps"
      - "ircs://chat.freenode.net:6697/#fedora-mote"
    template:
      - "[%{repository_name}:%{branch}@%{commit} - build #%{build_number}] CI %{result}! (%{build_url})"
    on_success: change
    on_failure: always
