---
name: mote
on: [push, pull_request, workflow_dispatch]

jobs:
  ci-basic:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v5

      - name: Install the base dependencies
        run: |
             python3 -m pip install --upgrade poetry tox ruff

      - name: Check the correctness of the project config
        run: |
             poetry check

      - name: Check the quality of the code
        run: |
             tox -e cleaning

  ci-tests:
    strategy:
      fail-fast: false
      matrix:
        tox-env: ["py38", "py39", "py310", "py311", "py312"]
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v5

      - name: Install the base dependencies
        run: |
             python3 -m pip install --upgrade tox

      - name: Install Redis
        run: |
             sudo dnf install redis -y

      - name: Set up user for running the testcases
        run: |
             useradd testuser
             chown -R testuser .

      - name: Execute tox
        env:
          FLASK_CACHE_REDIS_URL: "redis://localhost"
          FLASK_CACHE_TYPE: "RedisCache"
        run: |
             su testuser -c "tox -e ${{ matrix.tox-env }}"
